version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node-fetch"
    versions:
    - 2.5.8
    - 2.5.9
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: grpc
    versions:
    - 1.24.4
    - 1.24.5
    - 1.24.6
  - dependency-name: pino-pretty
    versions:
    - 4.3.0
    - 4.4.0
    - 4.5.0
    - 4.7.0
  - dependency-name: mime
    versions:
    - 2.5.0
  - dependency-name: "@dlghq/dialog-api"
    versions:
    - 1.85.0
    - 1.86.0
  - dependency-name: pino
    versions:
    - 6.11.0
  - dependency-name: "@types/pino"
    versions:
    - 6.3.5
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
  - dependency-name: ts-node
    versions:
    - 9.1.1
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: prettier
    versions:
    - 2.2.1
  - dependency-name: highlight.js
    versions:
    - 9.18.5
  - dependency-name: jest-junit
    versions:
    - 12.0.0
  - dependency-name: node-fetch
    versions:
    - 2.6.1
  - dependency-name: dot-prop
    versions:
    - 4.2.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: jquery
    versions:
    - 3.5.1
  - dependency-name: acorn
    versions:
    - 5.7.4
  - dependency-name: ts-jest
    versions:
    - 24.3.0
  registries:
  - npm-registry-registry-npmjs-org
